### ISSUE TITLE
Font installation for non-admin users

### ISSUE THREAD

**Issue by chawyehsu** [matthewjberger/scoop-nerd-fonts#10]
From Windows 10 17704 onward, Users have the ability to install fonts without admin rights.

As reference: https://blogs.windows.com/windowsexperience/2018/06/27/announcing-windows-10-insider-preview-build-17704/

**Comment by linyinfeng** [comment]
The work can be done by just replacing installer and uninstaller like this:
```
"installer": {
    "script": [
        "New-Item -Path 'HKCU:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts\\Scoop.%name' -Force | Out-Null",
        "Get-ChildItem `$dir -filter '*Windows Compatible.*' | ForEach-Object {",
        "    New-ItemProperty -Path 'HKCU:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts\\Scoop.%name' -Name `$_.Name -Value `$_.FullName -Force | Out-Null",
        "}"
    ]
},
"uninstaller": {
    "script": [
        "Remove-Item -Path 'HKCU:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts\\Scoop.%name'",
        "Write-Host \"The '`$(`$app.Replace('-NF', ''))' Font family has been uninstalled and will not be present after restarting your computer.\" -Foreground Magenta"
    ]
}
```

Changes made to registry will looks like this:
![2019-05-21](https://user-images.githubusercontent.com/11229748/58101437-34e21c80-7c12-11e9-8483-0fc4c90db3d6.png)

Also, changes to fonts can be immediately viewed in Settings - Personalization - Fonts.

My fork of the repository for my personal use installs fonts without admin rights: [linyinfeng/scoop-nerd-fonts](https://github.com/linyinfeng/scoop-nerd-fonts). I am not actively maintaining the fork and it may be buggy. But it can serves as a simple working example for the issue.

**Comment by h404bi** [comment]
@linyinfeng Thanks for your information, this is really helpful!
@matthewjberger Would you like to adopt this to support non-admin installation?

**Comment by linyinfeng** [comment]
@h404bi I don't known whether or not fonts installed by the new method can be used by any application. In my test some application can not use these fonts. I believe that compatibility of the new installation method needs more inspection. Maybe both installation methods should be kept.

**Comment by linyinfeng** [comment]
Tried to copy fonts to AppData\Local\Microsoft\Windows\Fonts and modified registry keys. Installed fonts in this directory seem work well.
Font files not in the directory seems take effect when fonts cache was rebuilt and disappear after system reboot. So maybe we can't just leave font files in the app directory of scoop and only create registry keys for them like the script described above in my comment, which I thought is a nice and clean way.
