### ISSUE TITLE
Source-Han-Mono-SC@1.002: hash check failed

### ISSUE THREAD

**Issue by xarthurx** [matthewjberger/scoop-nerd-fonts#100]
Checking hash of SourceHanMonoSC-Bold.otf ... ERROR Hash check failed!
App:         nerd-fonts/Source-Han-Mono-SC
URL:         https://github.com/adobe-fonts/source-han-mono/raw/master/Bold/OTC/SourceHanMonoSC-Bold.otf
First bytes: 4F 54 54 4F 00 11 01 00
Expected:    7bead3459a3afe4bcf4ce353cf639c13d54d3381bdb6ecaf58572ef4dac05091
Actual:      9c4ac2b19f68cf87068791af34dd5cd58dda76e4ea805c7e578ee9e967c42d96

**Comment by matthewjberger** [comment]
Try running `scoop cache rm *`

The hash in the manifest is correct, but I notice this issue happens sometimes for people with certain fonts. Feel free to reopen if this doesn't solve the problem for you!
