### ISSUE TITLE
Source-Han-Sans-SC@2.002: Hash check failed

### ISSUE THREAD

**Issue by Paxxs** [matthewjberger/scoop-nerd-fonts#105]
Hash check failed!
App:         nerd-fonts/Source-Han-Sans-SC
URL:         https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansSC.zip
First bytes: 80 75 3 4 20 0 0 0
Expected:    0982a91eb1446ef085108f8332537db4ad4e9509bd002a5fcf35288071290f38
Actual:      d23653e3a5ed75c49d86178277fd25ddbcd24226e829d5e0bdb3e63b171504c8

**Comment by matthewjberger** [comment]
Try running `scoop cache rm *` and reinstalling the font. That should fix the issue!
