### ISSUE TITLE
Source-Han-Sans-SC@2.004: Not installed to windows fonts folder

### ISSUE THREAD

**Issue by kele14x** [matthewjberger/scoop-nerd-fonts#113]
`sudo scoop install Source-Han-Sans-SC` runs successfully, but *.otf is not copied to windows fonts folder (eg. **C:\Windows\Fonts**).

It should be the installer script:

```ps1
"Get-ChildItem $dir -filter '*.otf'
```

fails, since *.otf files are not lie on the root folder, it's placed on **\<path-to-scoop\>\apps\Source-Han-Sans-SC\current\OTF\SimplifiedChinese**

**Comment by issaclin32** [comment]
Closing this issue because it has been solved.
