### ISSUE TITLE
Ability to install monospaced and non-monospaced fonts separately

### ISSUE THREAD

**Issue by Dreomite** [matthewjberger/scoop-nerd-fonts#16]
# General
Every patched font has [2 versions](https://github.com/ryanoasis/nerd-fonts/#features): fixed-width and double-width. The former has all icons fit into 1 cell, the later retains icons' ratio. Most people prefer the second option.

# The problem
Scoop installs 2 versions.

The user is supposed to install either of them, but not both. The fonts are named identically with the exception that one of them has `Mono` in its name. So you can set mono version explicitly, but not the other way around. This results in most (if not all) software on Windows (and Linux) using monospaced font version even if you define font name without `Mono` in it. Because of that, I have to manually install double-width font versions instead of using Scoop.

# Proposed solution
Add a separate `NF-mono` entry for every font and leave usual entries for double-width fonts, so it will correspond to original NF naming convention. Or add separate entry for double-width fonts as well, to retain backward compatibility.

You can tell monospaced and non-monospaced versions apart by replacing `*Windows Compatible.*` in [filtering query](https://github.com/matthewjberger/scoop-nerd-fonts/blob/aa9ea5e09735b913adfe6f35c19f2eec4ba3f902/bucket/Iosevka-NF.json#L15) to `*Mono Windows Compatible.*` and `*Complete Windows Compatible.*`

**Comment by matthewjberger** [comment]
Closed by https://github.com/matthewjberger/scoop-nerd-fonts/commit/6fe7b0c7c15bbf459f93c04759c1347547a5270b
