### ISSUE TITLE
Install font now showing up on wndows11 H2  22621 settings

### ISSUE THREAD

**Issue by jayagami** [matthewjberger/scoop-nerd-fonts#180]
Recently I upgrade my windows to 22621，which is believed the next windows release version.

Then I found  custom fonts not working in modern app when I restart computer.
It could be a windows bug.

But the problem is install nerd fonts with scoop not working at all.
You can found custom nerd font under control panel, but not in Windows Settings.

I have to install custom font with double click.

Maybe it's a system-related bug, but it could also be that the font installation method needs to be improved

**Comment by jonz94** [comment]
Hi, thanks for reporting the issue.

Today, I setup a VM with windows build 22621, and I could reproduce the issue on my end.

After some testing, I found the issue only occur when installing fonts as user font.

**Comment by jayagami** [comment]
> Hi, thanks for reporting the issue.
> 
> Today, I setup a VM with windows build 22621, and I could reproduce the issue on my end.
> 
> After some testing, I found the issue only occur when installing fonts as user font. If I install the fonts as system fonts (`sudo scoop install -g <fonts>`), the fonts will show up on Windows settings as expected.

Thank for your replying , `-g` option worked for me too.

But still loss custom font after reboot, waiting for a windows update.
BTW,  22621 is much improved and the animation is very smooth, so I can tolerate it.
