### ISSUE TITLE
somewhat confusing `uninstaller` script logging output

### ISSUE THREAD

**Issue by ZaLiTHkA** [matthewjberger/scoop-nerd-fonts#193]
so.. really silly one, but I just lost about 20 minutes trying to work out why `scoop update meslo-nf` told me:

> The 'meslo-nf' Font family has been uninstalled and will not be present after restarting your computer.

considering I was _updating_ this package, I most definitely not expected to see a message like that.

---

checking the manifest for this font package here, I worked out this is printed to the console host from [this line](https://github.com/matthewjberger/scoop-nerd-fonts/blob/9701067bb6984abd282c2b39bd4988dc2e8c0924/bucket/Meslo-NF.json#L49).

and while this makes perfect sense for _uninstalling_ the package, it is confusing for _updating_ the package, as per the following snippet:

```ps1
Updating 'meslo-nf' (2.1.0 -> 2.2.1)
Downloading new version
Meslo.zip (69,5 MB) [=======================================================================================================================================] 100%
Checking hash of Meslo.zip ... ok.
Uninstalling 'meslo-nf' (2.1.0)
Running uninstaller script...
The 'meslo-nf' Font family has been uninstalled and will not be present after restarting your computer.
Unlinking ~\scoop\apps\meslo-nf\current
Installing 'meslo-nf' (2.2.1) [64bit] from nerd-fonts bucket
Loading Meslo.zip from cache
Extracting Meslo.zip ... done.
Running installer script...
Linking ~\scoop\apps\meslo-nf\current => ~\scoop\apps\meslo-nf\2.2.1
'meslo-nf' (2.2.1) was installed successfully!
```

purely in the interest of avoiding future confusion, would it be possible to disable [this line](https://github.com/matthewjberger/scoop-nerd-fonts/blob/9701067bb6984abd282c2b39bd4988dc2e8c0924/bin/generate-manifests.ps1#L39) and re-generate this bucket's manifest files?

**Comment by jonz94** [comment]
Hi, thanks for the suggestion.

> while this makes perfect sense for uninstalling the package, it is confusing for updating the package

This is actually doable. [By checking the `$cmd` variable](https://github.com/ScoopInstaller/Scoop/wiki/Pre-Post-(un)install-scripts), we can know that the user is currently `uninstall` or `update` the font, and then disable the message when the current action is `update`.

**Comment by ZaLiTHkA** [comment]
> This is actually doable. [By checking the `$cmd` variable](https://github.com/ScoopInstaller/Scoop/wiki/Pre-Post-(un)install-scripts), we can know that the user is currently `uninstall` or `update` the font, and then disable the message when the current action is `update`.

as nifty as that is, in my opinion it's a little unnecessary.. if a user is _uninstalling_ something, then the natural result is that it "will not be present after restarting your computer". so basically, this message doesn't do anything to enhance the feedback from an "explicit uninstall" user action, and it only serves to confuse matters from an "explicit update" user action...

if there are no errors from running a command, then the action carried out by the explicit user command "just worked". so in my honest opinion: unless you can think of a good reason to keep this, I would say it's better to simply remove _that line_ and call it a day. :)

**Comment by matthewjberger** [comment]
The messages is meant to imply that the font is flagged for uninstallation but will stay on the system until the next restart. Fonts are unique in that way

**Comment by ZaLiTHkA** [comment]
> The message is meant to imply that the font is flagged for uninstallation but will stay on the system until the next restart. Fonts are unique in that way

thanks for the clarification.. _personally_, I still feel it's unnecessary. but that's the joy of opinions; they're free for everybody. (:

entirely up to you guys though. 🖖🏼
