### ISSUE TITLE
Is this related to nerd-fonts project?

### ISSUE THREAD

**Issue by Jogai** [matthewjberger/scoop-nerd-fonts#21]
@ryanoasis's [nerd-fonts](https://github.com/ryanoasis/nerd-fonts)

Because I thought it was, but it has considerably less fonts. Maybe explain  this in the readme.

**Comment by matthewjberger** [comment]
This repo has manifests for all of the fonts listed under the latest release of the nerd-fonts repo: https://github.com/ryanoasis/nerd-fonts/releases. It also has some that were in a prior release and some that were contributed to the repo by other developers. So what you really mean is that the nerd-fonts repo's release tag has considerably less fonts than what are listed in the repo's readme. If you want a specific font that isn't present though, open a separate issue and either myself or someone else will look into it.
