### ISSUE TITLE
Add LxgwNeoXiHei Font

### ISSUE THREAD

**Issue by ph3n92h3** [matthewjberger/scoop-nerd-fonts#218]
Hello, I want to suggest a new font.

> homepage: https://github.com/lxgw/LxgwNeoXiHei

**Comment by jonz94** [comment]
Hi @ph3n92h3,

I just add LxgwNeoXiHei Font.
You can use the following commands to install LxgwNeoXiHei Font:

```shell
scoop update
scoop install LXGWNeoXiHei
```
