### ISSUE TITLE
Add Martian mono

### ISSUE THREAD

**Issue by gaetschwartz** [matthewjberger/scoop-nerd-fonts#221]
Would be great if Martian mono could be added ! https://evilmartians.com/products/martian-mono

**Comment by jonz94** [comment]
Hi @gaetschwartz,

I just add Martian Mono Font.
You can use the following commands to install Martian Mono Font:

```shell
scoop update

# install ttf
scoop install Martian-Mono

# or install otf
scoop install Martian-Mono-otf
```
