### ISSUE TITLE
[Request] Maple-Font

### ISSUE THREAD

**Issue by sayeed205** [matthewjberger/scoop-nerd-fonts#225]
Font Name: Maple
GitHub: [Maple-font](https://github.com/subframe7536/Maple-font)
Stats: 1.6⭐ 28🍴

**Comment by jonz94** [comment]
Hi @sayeed205,

I just add the following fonts into the repository:

- `Maple-Mono`
- `Maple-Mono-otf`
- `Maple-Mono-NF`
- `Maple-Mono-SC-NF`
