### ISSUE TITLE
Nerd Fonts v3

### ISSUE THREAD

**Issue by jonz94** [matthewjberger/scoop-nerd-fonts#230]
Nerd Fonts v3 has just been released: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

Along with several breaking changes, it is important to note that the font file names have also been updated.

Therefore, we need to make changes to our code to reflect both the breaking changes and the new font file names.

**Comment by mattcargile** [comment]
After installing, _v3_ for  _CaskaydiaCove_, I noticed that

```powershell
(New-Object System.Drawing.Text.InstalledFontCollection).Families | sls cask
```
did not return the same thing as 

```powershell
Add-Type -AssemblyName PresentationCore
[Windows.Media.Fonts]::SystemFontFamilies | ? source -like caskay* | ft
```

Programs like _SQL Server Management Studio_, which don't allow you to pick a font name like _VSCode_ or the like, did not like the new _v3_ _CascadiaCode_ and would fail to use the font.

Here is the image from _SSMS_.

<img src="https://user-images.githubusercontent.com/74641867/236891547-c20763c1-4d7a-4f03-b74d-ce0dc087e42d.png" width="50%">

Here is the image from _Windows Settings_.

<img src="https://user-images.githubusercontent.com/74641867/236891629-83d835fc-b70f-4373-a1f1-7e0745d6b39f.png " width="70%">

All this to say, is there something wrong with my install or maybe CascadiaCode nerd fonts in general? Or some other incompatibility with certain Windows applications?

### NOTE
I was using `choco` for the uninstall/install.
