### ISSUE TITLE
LXGW-Bright@5.300, LXGW-Bright-GB@5.300, LXGW-Bright-TC: hash check failed

### ISSUE THREAD

**Issue by mksudo** [matthewjberger/scoop-nerd-fonts#233]
Checking hash of LXGWBright-Italic.otf ... ERROR Hash check failed!
App:         nerd-fonts/LXGW-Bright
URL:         https://raw.githubusercontent.com/lxgw/LxgwBright/main/LXGWBright/LXGWBright-Italic.otf
First bytes: 4F 54 54 4F 00 0C 00 80
Expected:    2ef52452a656149707a5b44ecf90c593796a8d3fadc1073320e3c62a4dcb5282
Actual:      250a02f9c9d88ad28ce0893b950a4c10742e34bd4ea4dbd7405c76edea05c1ee

Checking hash of LXGWBrightGB-Italic.otf ... ERROR Hash check failed!
URL:         https://raw.githubusercontent.com/lxgw/LxgwBright/main/LXGWBrightGB/LXGWBrightGB-Italic.otf
First bytes: 4F 54 54 4F 00 0C 00 80
Expected:    5f89bfa2f158a18fc6641d898dc4ea20bb8db108bee94218c9c3fb22d3cb355e
Actual:      6722dd235b8d938549de97c06025031cd0166e580483a205c27be45b60a658a9

Checking hash of LXGWBrightTC-Italic.otf ... ERROR Hash check failed!
App:         nerd-fonts/LXGW-Bright-TC
URL:         https://raw.githubusercontent.com/lxgw/LxgwBright/main/LXGWBrightTC/LXGWBrightTC-Italic.otf
First bytes: 4F 54 54 4F 00 0C 00 80
Expected:    8b5235ed5704d11f532edb4ac52f371cb173be696f019155d05f65fdb0a7950d
Actual:      1b6f181c6c5845033baf0a43222afefc5563131a156d36e6a43e15c6e918f6d0

**Comment by jonz94** [comment]
Reopen the issue because these manifests do have the wrong hash.
