### ISSUE TITLE
Add NerdFontsSymbolsOnly

### ISSUE THREAD

**Issue by Sacro** [matthewjberger/scoop-nerd-fonts#254]
Very handy as a fallback font!

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/NerdFontsSymbolsOnly

**Comment by jonz94** [comment]
Hi @Sacro,

I just add `NerdFontsSymbolsOnly` Font.
You can use the following commands to install it:

```shell
scoop update

scoop install NerdFontsSymbolsOnly
```

**Comment by Sacro** [comment]
Really sorry to be a pain, but could we have the -mono variant too? :)

**Comment by jonz94** [comment]
I put both normal and mono version in the same font manifest, so the command should install both of them for you.

**Comment by Sacro** [comment]
Oh yes! For some reason GoLand doesn't see it as monospace, I'll chase that up with them! Thanks!
