### ISSUE TITLE
[Request] Add monaspace

### ISSUE THREAD

**Issue by LucasOe** [matthewjberger/scoop-nerd-fonts#258]
Github Next has recently released a new set of fonts, [monaspace](https://github.com/githubnext/monaspace#monaspace). Because the font is still new it only has ~80 Starts at the point of writing this, but in my opinion, because it's from Github, it's important enough to be added.

**Comment by jonz94** [comment]
Hi,

I just add `Monaspace` Font.
Now, we can use the following commands to install it:

```shell
scoop update

scoop install Monaspace
```
