### ISSUE TITLE
Victor-Mono@1.5.6: hash check failed

### ISSUE THREAD

**Issue by fomlhaut** [matthewjberger/scoop-nerd-fonts#277]
Scoop output:
```
ERROR Hash check failed!
App:         nerd-fonts/Victor-Mono
URL:         https://rubjo.github.io/victor-mono/VictorMonoAll.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    eab377ad3bcc7a202697c024ebb8c8728f99789c4f093d358f3d202052cc9496
Actual:      16f327aa8f98137e1ff619c231c283e4cdc6a6f50027ca123cb58e8a79a8a095
```
What I've found is that the hash of the file `VictorMonoAll.zip` contained inside the ZIP file [https://github.com/rubjo/victor-mono/archive/refs/tags/v1.5.6.zip](https://github.com/rubjo/victor-mono/archive/refs/tags/v1.5.6.zip) is `eab377ad...`, but the hash of the file directly downloadable from [https://rubjo.github.io/victor-mono/VictorMonoAll.zip](https://rubjo.github.io/victor-mono/VictorMonoAll.zip) is `16f327aa...`.

Apart from that, both files contain the exact same folders and font files (after extraction, all the files are exactly the same, byte for byte). The only difference seems to be some bytes at the end of the ZIP files (maybe metadata?) which do not affect the files contained within.

**Comment by jonz94** [comment]
Thanks for the detailed information!

Now, installation scripts will directly download the zip file from GitHub, which should help avoid the `hash check failed` issue.
