### ISSUE TITLE
SarasaGothic@0.10.0: hash check failed

### ISSUE THREAD

**Issue by themrhead** [matthewjberger/scoop-nerd-fonts#28]
Checking hash of sarasa-gothic-ttf-0.10.0.7z ... ERROR Hash check failed!
App:         nerd-fonts/SarasaGothic
URL:         https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.10.0/sarasa-gothic-ttf-0.10.0.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    4f68e57015e0c18749e309af9fec649fd8faeb4de5bd036ec364ed051c3fd871
Actual:      ec0cf4a0d6b1b7a0d8bbb7835733361f96dce0f53e2b34ba526c18b700859f6c

**Comment by matthewjberger** [comment]
Thank you!
