### ISSUE TITLE
Cascadia Code is outdated

### ISSUE THREAD

**Issue by Sacro** [matthewjberger/scoop-nerd-fonts#33]
1910.04.01 is now out

**Comment by matthewjberger** [comment]
The manifest matches the latest release at https://github.com/microsoft/cascadia-code/releases so when a new release is made there I'll be able to update the manifest. Thank you though!

**Comment by Sacro** [comment]
Sorry, meant Delugia Code, I see that's updated now

**Comment by matthewjberger** [comment]
No problem! Thank you for contributing in the first place
