### ISSUE TITLE
Delugia-Nerd-Font-Complete@1910.04.1: hash check

### ISSUE THREAD

**Issue by ftenafmar** [matthewjberger/scoop-nerd-fonts#38]
Hi, I was trying to install it but shows this error:

`❯ sudo scoop install Delugia-Nerd-Font-Complete`
Installing 'Delugia-Nerd-Font-Complete' (1910.04.1) [64bit]
Delugia.Nerd.Font.Complete.ttf (913,5 KB) [===================================================================] 100%
Checking hash of Delugia.Nerd.Font.Complete.ttf ... ERROR Hash check failed!
App:         nerd-fonts/Delugia-Nerd-Font-Complete
URL:         https://github.com/adam7/delugia-code/releases/download/v1910.04.1/Delugia.Nerd.Font.Complete.ttf
First bytes: 00 01 00 00 00 12 01 00
Expected:    9b766cde4fd68aa0f710fb0742143f176a8b78f5a48cd42eab5877e533ee2900
Actual:      2784604f742c12f4ffaa72736e2661ff26070b595fb8c4ea2ce2a10e305612b7

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/matthewjberger/scoop-nerd-fonts/issues/new?title=Delugia-Nerd-Font-Complete%401910.04.1%3a+hash+check+failed

**Comment by matthewjberger** [comment]
Thank you!
