### ISSUE TITLE
Cascadia Code official powerline variants

### ISSUE THREAD

**Issue by kostrse** [matthewjberger/scoop-nerd-fonts#44]
Cascadia Code now shipped with official powerline variants:
```
CascadiaPL.ttf
CadcadiaMonoPL.ttf
```
https://github.com/microsoft/cascadia-code/releases/tag/v1911.21

Would it make sense to include them into the existing packages or as separated packages?

**Comment by matthewjberger** [comment]
I believe separated packages would make the most sense. It mostly comes down to whether the files are separated on the github release attachments and it looks like they are for Cascadia Code's github repo. I'll try to put up the manifests before I leave for Christmas 🎅
