### ISSUE TITLE
Missing Blex font

### ISSUE THREAD

**Issue by Sacro** [matthewjberger/scoop-nerd-fonts#7]
Available here https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Blex

**Comment by ViceIce** [comment]
Do you mean [IBMPlexMono](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/IBMPlexMono) ?

Is here [IBMPlexMono-NF](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/IBMPlexMono-NF.json)

**Comment by ViceIce** [comment]
@matthewjberger This is fixed and can be closed.
