### ISSUE TITLE
SarasaGothic-SC@0.12.14: hash check failed

### ISSUE THREAD

**Issue by tiange1949** [matthewjberger/scoop-nerd-fonts#86]
![image](https://user-images.githubusercontent.com/26919925/91565800-57b2c300-e975-11ea-97fc-724500eec483.png)

- **How to solve this problem?**

**Comment by matthewjberger** [comment]
Try this possibly:

```
scoop cache rm *
scoop uninstall sarasagothic-sc
scoop install sarasagothic-sc
```
