### ISSUE TITLE
ttc version of Sarasa Gothic

### ISSUE THREAD

**Issue by qcts33** [matthewjberger/scoop-nerd-fonts#9]
It's very nice to have Sarasa available. However, the whole ttf install is just huge. Can you provide a ttc version of the installer?
Also, the Sarasa have updated to 0.8.1

**Comment by matthewjberger** [comment]
I've updated `SarasaGothic` to `0.8.1` and added `SarasaGothic-ttc` to the manifests. It appears to install much faster than the ttf pack. Thank you for the suggestion!

**Comment by qcts33** [comment]
Sorry to bother you again, but there is a bug in the installer and uninstaller scripts that the 'sarasa*.ttf' should be 'sarasa*.ttc'

**Comment by matthewjberger** [comment]
No problem at all, I will fix this tomorrow morning

**Comment by matthewjberger** [comment]
I updated the manifest to use `ttc` instead of `ttf`. Thanks again for catching that! :smile:
