### ISSUE TITLE
Source-Han-Sans-SC@2.001: hash check failed

### ISSUE THREAD

**Issue by chengjiagan** [matthewjberger/scoop-nerd-fonts#92]
I think it's because source-han-sans has been updated to version 2.002 so the hash dosen't match.
![hash check failed](https://user-images.githubusercontent.com/4995759/98469487-eb78f900-221a-11eb-8b00-4197450c0d8f.png)

**Comment by matthewjberger** [comment]
Thank you for reporting! Should be fixed now
